import { Poppins, Plus_Jakarta_Sans } from 'next/font/google'
import localFont from "next/font/local"
import './globals.css'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins"
})
const jakarta_sans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-jakarta_sans"
})

const avenir = localFont({
  src: "../font/Avenir Regular.ttf",
  variable: "--font-anveir_regular"
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${jakarta_sans.variable} ${avenir.variable}`}>
        {children}
      </body>
    </html>
  )
}
